openapi: 3.0.0
info:
  version: "1.0.0"
  title: "fhtrust"
servers:
  -
    url: 'https://www.fhtrust.com.tw/FhtrustAPI/etfnav'
paths:
  /:
    get:
      parameters:
        - name: FundID
          in: query
          description: 基金代號
          required: true
          schema:
            type: string
        - name: sDate
          in: query
          description: '查詢開始時間 格式YYYY/MM/DD'
          required: true
          schema:
            type: string
            format: date
        - name: eDate
          in: query
          description: '查詢結束時間 格式YYYY/MM/DD'
          required: true
          schema:
            type: string
            format: date
      responses:
        200:
          description: '{200 response description}'
          headers:
            Content-Type:
              schema:
                type: string
                enum:
                  - application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    description: 結果
                    type: array
                    items:
                      type: object
                      properties:
                        fundID:
                          description: 基金代號
                          type: string
                        pnav:
                          description: 淨值
                          type: number
                        navDate:
                          description: 淨值日期
                          type: string
                          format: date
                        change:
                          description: 漲跌
                          type: number
                        changeRange:
                          description: 單日漲跌幅(%)
                          type: number
                        changeRangeAcc:
                          description: 累積漲跌幅(%)
                          type: number
                        qnav_l:
                          description: 淨值小數位數
                          type: integer
                        FunNav:
                          description: 基本面額
                          type: number
                          nullable: true
                        eq_Income:
                          description: 收益平準金
                          type: number
                          nullable: true
                        eq_Cap:
                          description: 資本損益益平準金
                          type: number
                          nullable: true
                        eq_Interest:
                          description: 利息淨收入
                          type: number
                          nullable: true
                        eq_Dividend:
                          description: 股利淨收入
                          type: number
                          nullable: true
                      required:
                        - fundID
                        - pnav
                        - navDate
                        - change
                        - changeRange
                        - changeRangeAcc
                        - qnav_l
                  # status:
                  #   description: 狀態
                  #   type: integer
                  # responseStatus:
                  #   description: 回應狀態
                  #   type:
                  #     - number
                  #     - 'null'
                required:
                  - result
                  # - status
